// Extensions to videojs' German locale go here.

videojs.addLanguage("de", {
	"Time": "Zeit",
	"Go to this Position": "Gehe zu Position",
	"Copy to Clipboard": "In Zwischenablage kopieren",
	"Hint": "Hinweis",
	"Hints": "Hinweise",
	"Settings": "Einstellungen",
	"Language": "Sprache",
	"Language Menu": "Sprachmenü",
	"none": "keine",
	"Audio / Video": "Ton und Bild",
	"Extras": "Extras",
	"Subtitles": "Untertitel",
	"No other languages available.": "Keine anderen Sprachen verfügbar.",

	"Afrikaans": "Afrikaans",
	"Arabic": "Arabisch",
	"Bashkir": "Baschkirisch",
	"Bulgarian": "Bulgarisch",
	"Catalan": "Katalanisch",
	"Czech": "Tschechisch",
	"Danish": "Dänisch",
	"German": "Deutsch",
	"English": "Englisch",
	"Spanish (Spain)": "Spanish (Spain)",
	"Finnish": "Finnisch",
	"French": "Franzesisch",
	"Croatian": "Kroatisch",
	"Hungarian": "Ungarisch",
	"Italian": "Italienisch",
	"Japanese": "Japanisch",
	"Korean": "Koreanisch",
	"Dutch": "Niderländisch",
	"Portuguese": "Portugiesisch",
	"Portuguese (Brazil)": "Portugiesisch (Brasilien)",
	"Russian": "Russisch",
	"Serbian": "Serbisch",
	"Swedish": "Schwedisch",
	"Turkish": "Türkisch",
	"Ukrainian": "Ukrainisch",
	"Vietnamese": "Vietnamesisch",
	"Chinese (PRC)": "Chinesisch (PRC)",
	"Chinese (Taiwan)": "Chinesisch (Taiwan)",
});