// Extensions to videojs' locale go here.

videojs.addLanguage("es",{
	"Afrikaans": "Afrikaans",
	"Arabic": "Árabe",
	"Bashkir": "Baskir",
	"Bulgarian": "Búlgaro",
	"Catalan": "Catalán",
	"Czech": "Checo",
	"Danish": "Danés",
	"German": "Alemán",
	"English": "Inglés",
	"Spanish": "Spanish (Spain)",
	"Finnish": "Finés",
	"French": "Francés",
	"Croatian": "Croata",
	"Hungarian": "Húngaro",
	"Italian": "Italiano",
	"Japanese": "Japonés",
	"Korean": "Coreano",
	"Dutch": "Neerlandés",
	"Portuguese": "Portugués",
	"Portuguese (Brazil)": "Portugués (Brazil)",
	"Russian": "Ruso",
	"Serbian": "Serbio",
	"Swedish": "Sueco",
	"Turkish": "Turco",
	"Ukrainian": "Ucraniano",
	"Vietnamese": "Vietnamita",
	"Chinese (PRC)": "Chino (PRC)",
	"Chinese (Taiwan)": "Chino (Taiwan)",
});