// Extensions to videojs' German locale go here.

videojs.addLanguage("fr",{
	"Afrikaans": "Afrikaans",
	"Arabic": "Arabe",
	"Bashkir": "Bachkir",
	"Bulgarian": "Bulgare",
	"Catalan": "Catalan",
	"Czech": "Tchèque",
	"Danish": "Danois",
	"German": "Allemand",
	"English": "Anglais",
	"Spanish": "Spanish (Spain)",
	"Finnish": "Finnois",
	"French": "Français",
	"Croatian": "Croate",
	"Hungarian": "Hongrois",
	"Italian": "Italien",
	"Japanese": "Japonais",
	"Korean": "Coréen",
	"Dutch": "Néerlandais",
	"Portuguese": "Portugais",
	"Portuguese (Brazil)": "Portugais (Brazil)",
	"Russian": "Russe",
	"Serbian": "Serbe",
	"Swedish": "Suédois",
	"Turkish": "Turc",
	"Ukrainian": "Ukrainien",
	"Vietnamese": "Vietnamien",
	"Chinese (PRC)": "Chinois (PRC)",
	"Chinese (Taiwan)": "Chinois (Taiwan)",
});