// Extensions to videojs' locale go here.

videojs.addLanguage("it",{
	"Afrikaans": "Afrikaans",
	"Arabic": "Arabo",
	"Bashkir": "Baschiro",
	"Bulgarian": "Bulgaro",
	"Catalan": "Catalano",
	"Czech": "Ceco",
	"Danish": "Danese",
	"German": "Tedesco",
	"English": "English",
	"Spanish": "Spanish (Spain)",
	"Finnish": "Finlandese",
	"French": "Francese",
	"Croatian": "Croato",
	"Hungarian": "Ungherese",
	"Italian": "Inglese",
	"Japanese": "Giapponese",
	"Korean": "Coreano",
	"Dutch": "Olandese",
	"Portuguese": "Portoghese",
	"Portuguese (Brazil)": "Portoghese (Brazil)",
	"Russian": "Russo",
	"Serbian": "Serbo",
	"Swedish": "Svedese",
	"Turkish": "Turco",
	"Ukrainian": "Ucraino",
	"Vietnamese": "Vietnamita",
	"Chinese (PRC)": "Cinese (PRC)",
	"Chinese (Taiwan)": "Cinese (Taiwan)",
});