// Extensions to videojs' German locale go here.

videojs.addLanguage("pt-BR",{
	"Afrikaans": "Africânder",
	"Arabic": "Árabe",
	"Bashkir": "Baxequir",
	"Bulgarian": "Búlgaro",
	"Catalan": "Catalão",
	"Czech": "Tcheco",
	"Danish": "Dinamarquês",
	"German": "Alemão",
	"English": "Inglês",
	"Spanish": "Spanish (Spain)",
	"Finnish": "Finlandês",
	"French": "Francês",
	"Croatian": "Croata",
	"Hungarian": "Húngaro",
	"Italian": "Italiano",
	"Japanese": "Japonês",
	"Korean": "Coreano",
	"Dutch": "Holandês",
	"Portuguese": "Português",
	"Portuguese (Brazil)": "Português (Brazil)",
	"Russian": "Russo",
	"Serbian": "Sérvio",
	"Swedish": "Sueco",
	"Turkish": "Turco",
	"Ukrainian": "Ucraniano",
	"Vietnamese": "Vietnamita",
	"Chinese (PRC)": "Chinês (PRC)",
	"Chinese (Taiwan)": "Chinês (Taiwan)",
});